### ISSUE TITLE
Dont start for me

### ISSUE THREAD

**Issue by deepvape** [Porting-Dead-Mods/Cable-Facades#1]
Unfortunately the mod doesn't work for me. Game crashes when I install mod. Attached is the log.

[latest.log](https://github.com/user-attachments/files/17780524/latest.log)

**Comment by Thepigcat76** [comment]
yup, will put out a fix shortly :+1:

**Comment by Leclowndu93150** [comment]
The fix is out already

**Comment by deepvape** [comment]
It works great, but when you remove the blocks in creative you get the block back but the cable underneath is gone. or do you have to remove it with the wrench?

**Comment by Leclowndu93150** [comment]
you're in creative mode bruh

**Comment by deepvape** [comment]
yes, but can you perhaps do it in such a way that you only remove the facade block and not the cable?

**Comment by Leclowndu93150** [comment]
yeah
