### ISSUE TITLE
Facades are not synced when player changes dimensions

### ISSUE THREAD

**Issue by SuperMartijn642** [Porting-Dead-Mods/Cable-Facades#10]
The player receives the cable facades once when they log in and that's it. If the player changes dimensions, the facades are not resend and thus the player sees facades from the dimension they were in when they joined and no matter what dimension they are actually in.

A solution would be sending the facades for the new dimension during the `PlayerChangedDimensionEvent` and `PlayerRespawnEvent` events.

**Comment by Thepigcat76** [comment]
should be fixed as well
