### ISSUE TITLE
Crash when placing Facade on dedicated server

### ISSUE THREAD

**Issue by furtabs** [Porting-Dead-Mods/Cable-Facades#18]
https://gist.github.com/EndangeredNayla/0b7e5aa2f06000dea73b385aa6dab7fa

**Comment by Leclowndu93150** [comment]
good timing as we just rewrote entirely the mod, we are doing server testings right now and making sure everything works. 
then we'll move from beta to a release state. should be in a few hours

**Comment by Thepigcat76** [comment]
should be fixed in the latest version
