### ISSUE TITLE
Facade Render not work correct

### ISSUE THREAD

**Issue by Reaviik** [Porting-Dead-Mods/Cable-Facades#20]
When I place the facade in a world and invite a player from another dimension to come to me, he simply does not see the facades, even after restarting the server or re-entering the world. The same does not happen when the other player is next to me, even after restarting or re-entering he continues to see normally.

I'm currently using Arclight with fork and Embedium/Oculos

**Comment by Thepigcat76** [comment]
Are you using the latest version?

**Comment by Reaviik** [comment]
yes, 1.1.0

**Comment by Thepigcat76** [comment]
That is not the latest version. Please update  to 1.1.1 and see if that fixes the issue.

**Comment by Reaviik** [comment]
I'm sorry I forgot to mention that I was using forge, the latest version for forge is 1.1.0, however I will test 1.1.1

**Comment by Thepigcat76** [comment]
Yea sorry, that was an issue on our side, the version was labelled incorrectly
