### ISSUE TITLE
Crash when right-clicking a facade stair with the facade wrench

### ISSUE THREAD

**Issue by MuteTiefling** [Porting-Dead-Mods/Cable-Facades#22]
1. make a facade look like a stair
2. place it on a powah cable
3. right click the facade with the facade wrench

Latest: https://mclo.gs/FF597nX
Debug: https://mclo.gs/IRODQDz

**Comment by MuteTiefling** [comment]
Can't reproduce, but figured I'd report anyway

**Comment by Thepigcat76** [comment]
yea weird issue, will close for now. You can reopen it, if it happens again
