### ISSUE TITLE
Crash when using Ars Nouveau spells near bedrock

### ISSUE THREAD

**Issue by MuteTiefling** [Porting-Dead-Mods/Cable-Facades#26]
Bit of an odd one, but I can't reproduce this without Cable Facades installed. 

Crash log: https://mclo.gs/qHbOShd

I'm mining with the following spell near bedrock. 
![image](https://github.com/user-attachments/assets/3b423bac-0413-45cf-95eb-55071577eb69)

If I cast too close to bedrock, the game crashes. It's as if the spell is chaining under bedrock and then encounters an issue with cable facades?

**Comment by Leclowndu93150** [comment]
oh i see
