### ISSUE TITLE
Placing an energizing rod on facade cables from powah crashes a server 

### ISSUE THREAD

**Issue by MrEizy** [Porting-Dead-Mods/Cable-Facades#28]
Placing an energizing rod on facade cables from powah crashes a server you can still log back in but it just kicks you

**Comment by Leclowndu93150** [comment]
logs ? crash reports ?

**Comment by Leclowndu93150** [comment]
![2024-12-24_19 43 12](https://github.com/user-attachments/assets/6dfc7e95-c822-402d-9ec1-25c73398307f)
