### ISSUE TITLE
Touching transparent blocks causes face to not render

### ISSUE THREAD

**Issue by chloeseitz27** [Porting-Dead-Mods/Cable-Facades#29]
First off, great mod :)

I've noticed 2 separate but similar issues. Minecraft 1.21.1, NeoForge 21.1.87, LWJGL 3.3.3, Cable Facades 1.2.0

The first one is that connected textures through the fusion mod seem to cause faces not to render (this only happens when shaders are disabled, shaders make this issue go away). You can see the second issue in these pictures as well.
![2024-12-21_12 22 57](https://github.com/user-attachments/assets/02b98ee7-1d5d-4318-891f-b830dfde1d01)
![2024-12-21_12 23 03](https://github.com/user-attachments/assets/6486c318-bb22-4016-851b-5286b46b5b11)

The second one is simply that water on these blocks makes them misbehave. It doesn't seem to be tied to any mods as far as I can tell, I ran this mod with just mekanism on a plain neoforge and it was still happening. ![2024-12-21_17 55 59](https://github.com/user-attachments/assets/716a61ee-a449-472a-b1a9-9d5ca62dd22b)

**Comment by Leclowndu93150** [comment]
thanks for the report !
this hopefuly is a simple fix

**Comment by SuperMartijn642** [comment]
I believe the first issue mentioned is probably just a Fusion bug similar to what is reported here https://github.com/SuperMartijn642/Fusion/issues/82. I have already fixed that issue, but it is part of a larger update which I have not yet published. That update will likely fix it.

**Comment by Leclowndu93150** [comment]
fixed in 1.3.0
