### ISSUE TITLE
Config options aren't synced

### ISSUE THREAD

**Issue by SuperMartijn642** [Porting-Dead-Mods/Cable-Facades#9]
If the config options of blocks which are allowed to have facades differs between the client and the server, the client may not be able to place facades on blocks allowed by the server or the client may place facades on blocks not allowed by the server leading to desyncs of facades.

**Comment by DataDalton** [comment]
Can confirm in testing

**Comment by SuperMartijn642** [comment]
Just to note, what I mentioned in #11 would also mitigate this issue:
Ideally, the check to see whether a facade can be placed would only be done server-side and if the facade is placed, it should then be synced to the clients nearby. This would also avoid a situation where the client and server disagree on whether a facade could be placed.
